apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-lounge
resources:
  - common/registry-secret.yaml
  - projects.yaml
  - ai-apps.yaml
  - overlays/cloudflare
  - overlays/hello-ai
  - overlays/nabijiyo
  - overlays/postgres

