apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-lounge
resources:
  - projects.yaml
  - ai-apps.yaml
  - overlays/cloudflare
  - overlays/hello-ai
  - overlays/nabijiyo

