apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-lounge
resources:
  - db-secret.yaml
  - deployment.yaml
  - service.yaml
  - migrate-job.yaml
images:
  - name: nabijiyo
    newName: registry.prup.xyz/ai-lounge/nabijiyo
    newTag: latest
