apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-lounge
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: nabijiyo
    newName: ${REGISTRY_URL}/ai-lounge/nabijiyo
    newTag: latest
