apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-lounge
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: hello-ai
    newName: registry.prup.xyz/ai-lounge/hello-ai
    newTag: latest
