apiVersion: v1
kind: Service
metadata:
  name: hello-ai
  namespace: ai-lounge
  labels:
    app: hello-ai
spec:
  type: ClusterIP
  selector:
    app: hello-ai
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http

