apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-lounge
resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: chat-history-viewer
    newName: registry.prup.xyz/ai-lounge/chat-history-viewer
    newTag: v202602081704
