apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-lounge
resources:
  - ../../../apps/cloudflare
  - secret.yaml
commonLabels:
  app.kubernetes.io/component: cloudflare
  app.kubernetes.io/managed-by: argocd
