apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-lounge
bases:
  - ../../../apps/cloudflare
secretGenerator:
  - name: cloudflared-token
    envs:
      - .env
commonLabels:
  app.kubernetes.io/component: cloudflare
  app.kubernetes.io/managed-by: argocd
generatorOptions:
  disableNameSuffixHash: true
