apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-lounge
resources:
  - secret.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ai-image-generator
    newName: registry.prup.xyz/ai-lounge/ai-image-generator
    newTag: v202602081657
