apiVersion: v1
kind: Service
metadata:
  name: ai-image-generator
  namespace: ai-lounge
  labels:
    app: ai-image-generator
spec:
  type: ClusterIP
  selector:
    app: ai-image-generator
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
